# Generated by Django 2.2.2 on 2019-12-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xftools',
            new_name='xftool',
        ),
    ]
