# Generated by Django 2.2.2 on 2019-12-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20191211_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='xftool',
            name='image',
            field=models.ImageField(default='', upload_to='tools/images'),
        ),
        migrations.AlterField(
            model_name='xftool',
            name='tool_name',
            field=models.CharField(max_length=50),
        ),
    ]
