# Generated by Django 2.2.2 on 2019-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20191211_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='xftool',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xftool',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xftool',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
