# Generated by Django 2.2.2 on 2019-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20191212_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xftool',
            name='department',
            field=models.CharField(choices=[('AG_LEARN', 'Agilent Learning'), ('IQC', 'Instrument QC'), ('CQC', 'Cartridge QC'), ('SP', 'Spotting'), ('METRO', 'Metrology')], default='Agilent Learning', max_length=50),
        ),
    ]
