# Generated by Django 3.2.8 on 2021-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20191217_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xftool',
            name='subcategory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
